### ISSUE TITLE
Unable to use SMTP port 25; insecure connections not supported

### ISSUE THREAD

**Issue by abstrusemoose** [Kareadita/KavitaEmail#12]
I keep an insecure SMTP mail server on a secured local network, using standard port 25. Kavita is configured with Kavita-email using docker. The systems are connected and in the Kavita E-mail tab, the Test shows 'Email service URL validated'.

When an email is attempted to be sent, the logs in the Kavita-email service throws the following error:

===

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMKRDEDNFKCA", Request id "0HMKRDEDNFKCA:00000002": An unhandled exception was thrown by the application.
      System.Net.Mail.SmtpException: Server does not support secure connections.
         at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendEHelloCallback(IAsyncResult result)

===

**Comment by majora2007** [comment]
I think you just need to enable this setting in appsettings.json: "EnableSsl": true,

Can you validate that for me?

**Comment by abstrusemoose** [comment]
Unfortunately not, sir. Setting was changed to true in Kavita appsettings.json, restarted, and tested. Also then tested setting it to 'false', with no luck.

Perhaps I should clarify... my SMTP server does not support secure connections. The logs in the Kavita-email app also reflect this, as above. Is there any way for the Kavita-email app to support unencrypted SMTP communication over port 25?

Thank you for your help!

**Comment by abstrusemoose** [comment]
Some further information:

If I set "EnableSsl": false, in appsettings.json, and restart the container, the first request from Kavita to send an email will work, the email will be sent and delivered without any error.

However, for each subsequent attempt to send an email after this one - to any email address - will show as sent in the Kavita GUI, however no email is sent, and the following error (posted below) is found in KavitaEmail logs. This error will occur for each time an email is attempting to send after this point, just with different 'Request id's. When I restart the KavitaEmail container, the first email will be delivered, then will fail again for each email after that.

Here is the full error from KavitaEmail for the every email send request that isn't the first after container restart:

`
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMKRP70EKBD0", Request id "0HMKRP70EKBD0:00000003": An unhandled exception was thrown by the application.
      System.Net.Mail.SmtpException: Server does not support secure connections.
         at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendEHelloCallback(IAsyncResult result)
      --- End of stack trace from previous location ---
         at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
         at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
      --- End of stack trace from previous location ---
         at Skeleton.Services.EmailService.SendEmail(EmailOptionsDto userEmailOptions) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Services/EmailService.cs:line 118
         at Skeleton.Services.EmailService.SendEmailMigrationEmail(EmailMigrationDto dto) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Services/EmailService.cs:line 68
         at Skeleton.Controllers.EmailController.SendEmailMigrationEmail(EmailMigrationDto dto) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Controllers/EmailController.cs:line 61
         at lambda_method12(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Skeleton.Startup.<>c.<<Configure>b__4_1>d.MoveNext() in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Startup.cs:line 111
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
`
Thanks!

**Comment by majora2007** [comment]
What port are you using? From a quick Google search, using 587 might solve your problem. I know for using gmail, there are different ports for https or just http.

**Comment by majora2007** [comment]
I'm going to close this as you never got back. If you need help reopen.
