### ISSUE TITLE
Mail Not Sending / Crashing Service

### ISSUE THREAD

**Issue by MrMysterius** [Kareadita/KavitaEmail#3]
Don't know much about C# but this doesn't seem healthy

```
[40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
[40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
No XML encryptor configured. Key {27aa13bb-d718-43fe-aa39-6ba121a84e30} may be persisted to storage in unencrypted form.
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[14]
Now listening on: http://[::]:5003
Kavita Email Service has started up
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
Application started. Press Ctrl+C to shut down.
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
Hosting environment: Production
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
Content root path: /app
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]
Connection id "0HMG2NF2VCG7P", Request id "0HMG2NF2VCG7P:00000002": An unhandled exception was thrown by the application.
System.Net.Mail.SmtpException: Failure sending mail.
---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult)
at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback(IAsyncResult result)
--- End of stack trace from previous location ---
at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
--- End of inner exception stack trace ---
at Skeleton.Services.EmailService.SendEmail(EmailOptionsDto userEmailOptions) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Services/EmailService.cs:line 118
at Skeleton.Services.EmailService.SendEmailMigrationEmail(EmailMigrationDto dto) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Services/EmailService.cs:line 68
at Skeleton.Controllers.EmailController.SendEmailMigrationEmail(EmailMigrationDto dto) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Controllers/EmailController.cs:line 61
at lambda_method12(Closure , Object )
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Skeleton.Startup.<>c.<<Configure>b__4_1>d.MoveNext() in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Startup.cs:line 111
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]
Connection id "0HMG2NF2VCG7P", Request id "0HMG2NF2VCG7P:00000002": An unhandled exception was thrown by the application.
System.Net.Mail.SmtpException: Failure sending mail.
---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult)
at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback(IAsyncResult result)
--- End of stack trace from previous location ---
at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
--- End of inner exception stack trace ---
at Skeleton.Services.EmailService.SendEmail(EmailOptionsDto userEmailOptions) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Services/EmailService.cs:line 118
at Skeleton.Services.EmailService.SendEmailMigrationEmail(EmailMigrationDto dto) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Services/EmailService.cs:line 68
at Skeleton.Controllers.EmailController.SendEmailMigrationEmail(EmailMigrationDto dto) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Controllers/EmailController.cs:line 61
at lambda_method12(Closure , Object )
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Skeleton.Startup.<>c.<<Configure>b__4_1>d.MoveNext() in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Startup.cs:line 111
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by majora2007** [comment]
This looks like an issue where your SMTP service was not found. 

`An unhandled exception was thrown by the application.
System.Net.Mail.SmtpException: Failure sending mail.
---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known`

https://stackoverflow.com/questions/63712606/socketexception-name-or-service-not-known-when-url-loads-fine-in-browser

Maybe if your SMTP service is in another docker container? Can you give some more context on this?

**Comment by MrMysterius** [comment]
I use a google account for sending mail over their smtp

**Comment by majora2007** [comment]
Interesting. I do as well and no issues like this in our logs yet. Was the email successfully sending or no? For google, you have to allow insecure apps to use it for SMTP.

**Comment by MrMysterius** [comment]
Ok I relooked into my setting found it had `smpt.gmail.com` instead of `smtp.gmail.com` changed that, but now it's still not working

```
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]
Connection id "0HMG2NVB1LQVD", Request id "0HMG2NVB1LQVD:00000002": An unhandled exception was thrown by the application.
System.Net.Mail.SmtpException: Syntax error, command unrecognized. The server response was:

at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
--- End of stack trace from previous location ---
at Skeleton.Services.EmailService.SendEmail(EmailOptionsDto userEmailOptions) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Services/EmailService.cs:line 118
at Skeleton.Services.EmailService.SendEmailMigrationEmail(EmailMigrationDto dto) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Services/EmailService.cs:line 68
at Skeleton.Controllers.EmailController.SendEmailMigrationEmail(EmailMigrationDto dto) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Controllers/EmailController.cs:line 61
at lambda_method12(Closure , Object )
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Skeleton.Startup.<>c.<<Configure>b__4_1>d.MoveNext() in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Startup.cs:line 111
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by MrMysterius** [comment]
> Interesting. I do as well and no issues like this in our logs yet. Was the email successfully sending or no? For google, you have to allow insecure apps to use it for SMTP.

Also I use the account for other apps email use aswell it works fine on them it's just kavita atm

**Comment by MrMysterius** [comment]
Found the issue it doesn't work with the SSL port `465` from Google just TLS `587`

**Comment by MrMysterius** [comment]
> Found the issue it doesn't work with the SSL port `465` from Google just TLS `587`

Maybe worth noting in documentation/readme that TLS only works or something like that.
