### ISSUE TITLE
Cannot send book to Kindle

### ISSUE THREAD

**Issue by lawliet616** [Kareadita/KavitaEmail#31]
I've setup kavita and kavita-email ina docker-compose stack. 

```
  kavita-email:
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    image: kizaing/kavitaemail:latest
    container_name: kavita-email
    environment:
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: $MY_EMAIL
      SMTP_PASS: $GOOGLE_APP_PASSWORD
      SEND_ADDR: $MY_EMAIL
      DISP_NAME: Gmail
      ALLOW_SENDTO: "true"
      SIZE_LIMIT: 26214400
```

Email service URL in kavita is `http://kavita-email:5003`.

When I try to send a book to my Kindle I get the following error:
`System.Net.Mail.SmtpException: Syntax error, command unrecognized. The server response was:`

Full stacktrace:
```
kavita-email     | 2023-02-14T16:55:13.838492393Z [KavitaEmail] [2023-02-14 16:55:13.837 +00:00  ] [Error] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/sendto responded 500 in 10197.4157 ms
kavita-email     | 2023-02-14T16:55:13.838531156Z System.Net.Mail.SmtpException: Syntax error, command unrecognized. The server response was:
kavita-email     | 2023-02-14T16:55:13.838550084Z    at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
kavita-email     | 2023-02-14T16:55:13.838561608Z    at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
kavita-email     | 2023-02-14T16:55:13.838577741Z --- End of stack trace from previous location ---
kavita-email     | 2023-02-14T16:55:13.838593596Z    at Skeleton.Services.EmailService.SendEmail(EmailOptionsDto userEmailOptions) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Services/EmailService.cs:line 166
kavita-email     | 2023-02-14T16:55:13.838607285Z    at Skeleton.Services.EmailService.SendToDevice(String emailAddress, IList`1 attachments) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Services/EmailService.cs:line 127
kavita-email     | 2023-02-14T16:55:13.838619717Z    at Skeleton.Controllers.SendToController.UploadAndSend(IFormCollection formCollection) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Controllers/SendToController.cs:line 89
kavita-email     | 2023-02-14T16:55:13.838648213Z    at lambda_method12(Closure , Object )
kavita-email     | 2023-02-14T16:55:13.838658759Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
kavita-email     | 2023-02-14T16:55:13.838669585Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
kavita-email     | 2023-02-14T16:55:13.838681319Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
kavita-email     | 2023-02-14T16:55:13.838699548Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
kavita-email     | 2023-02-14T16:55:13.838715192Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
kavita-email     | 2023-02-14T16:55:13.838727694Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
kavita-email     | 2023-02-14T16:55:13.838740476Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
kavita-email     | 2023-02-14T16:55:13.838751930Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
kavita-email     | 2023-02-14T16:55:13.838761079Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
kavita-email     | 2023-02-14T16:55:13.838771975Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
kavita-email     | 2023-02-14T16:55:13.838783918Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
kavita-email     | 2023-02-14T16:55:13.838800122Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
kavita-email     | 2023-02-14T16:55:13.838815906Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
kavita-email     | 2023-02-14T16:55:13.838826871Z    at Skeleton.Startup.<>c.<<Configure>b__4_1>d.MoveNext() in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Startup.cs:line 122
kavita-email     | 2023-02-14T16:55:13.838838256Z --- End of stack trace from previous location ---
kavita-email     | 2023-02-14T16:55:13.838848313Z    at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
kavita-email     | 2023-02-14T16:55:13.842544683Z [KavitaEmail] [2023-02-14 16:55:13.840 +00:00  ] [Error] Microsoft.AspNetCore.Server.Kestrel Connection id "0HMOELGCSMRCO", Request id "0HMOELGCSMRCO:00000003": An unhandled exception was thrown by the application.
kavita-email     | 2023-02-14T16:55:13.842821540Z System.Net.Mail.SmtpException: Syntax error, command unrecognized. The server response was:
kavita-email     | 2023-02-14T16:55:13.842963601Z    at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
kavita-email     | 2023-02-14T16:55:13.843159022Z    at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
kavita-email     | 2023-02-14T16:55:13.843986801Z --- End of stack trace from previous location ---
kavita-email     | 2023-02-14T16:55:13.844119782Z    at Skeleton.Services.EmailService.SendEmail(EmailOptionsDto userEmailOptions) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Services/EmailService.cs:line 166
kavita-email     | 2023-02-14T16:55:13.844315202Z    at Skeleton.Services.EmailService.SendToDevice(String emailAddress, IList`1 attachments) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Services/EmailService.cs:line 127
kavita-email     | 2023-02-14T16:55:13.844328612Z    at Skeleton.Controllers.SendToController.UploadAndSend(IFormCollection formCollection) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Controllers/SendToController.cs:line 89
kavita-email     | 2023-02-14T16:55:13.844337203Z    at lambda_method12(Closure , Object )
kavita-email     | 2023-02-14T16:55:13.844345724Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
kavita-email     | 2023-02-14T16:55:13.844356829Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
kavita-email     | 2023-02-14T16:55:13.844365280Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
kavita-email     | 2023-02-14T16:55:13.844373870Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
kavita-email     | 2023-02-14T16:55:13.844380506Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
kavita-email     | 2023-02-14T16:55:13.844389725Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
kavita-email     | 2023-02-14T16:55:13.844403414Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
kavita-email     | 2023-02-14T16:55:13.844412005Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
kavita-email     | 2023-02-14T16:55:13.844418780Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
kavita-email     | 2023-02-14T16:55:13.844432469Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
kavita-email     | 2023-02-14T16:55:13.844441129Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
kavita-email     | 2023-02-14T16:55:13.844523823Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
kavita-email     | 2023-02-14T16:55:13.844540376Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
kavita-email     | 2023-02-14T16:55:13.844592968Z    at Skeleton.Startup.<>c.<<Configure>b__4_1>d.MoveNext() in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Startup.cs:line 122
kavita-email     | 2023-02-14T16:55:13.844608683Z --- End of stack trace from previous location ---
kavita-email     | 2023-02-14T16:55:13.844651566Z    at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
kavita-email     | 2023-02-14T16:55:13.844666303Z    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
kavita-email     | 2023-02-14T16:55:13.844712190Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
kavita-email     | 2023-02-14T16:55:13.844730978Z    at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
kavita-email     | 2023-02-14T16:55:13.844803824Z    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
kavita-email     | 2023-02-14T16:55:13.844816256Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
kavita-email     | 2023-02-14T16:55:13.844825196Z [KavitaEmail] [2023-02-14 16:55:13.842 +00:00  ] [Information] Microsoft.AspNetCore.Hosting.Diagnostics Request finished HTTP/1.1 POST http://kavita-email:5003/api/sendto multipart/form-data;+boundary="ee49804d-5096-4173-80d6-6f8985752845" - - 500 0 - 10205.9484ms
```

The same setup works with Calibre on Windows.

Do you have any idea what is the problem here?
Thank you!

**Comment by majora2007** [comment]
If you search around, you'll see this is a common issue. You either are a) Using the wrong port from google or b) have not allowed insecure apps and aren't using an app password. 

Search the existing issues and report back.

**Comment by lawliet616** [comment]
Thanks for the quick feedback!

I've checked existing issues, tried all of the SMTP ports (25, 465, 587, 2525) and also created a brand new app-password for Kavita before submitting the ticket.

"insecure apps" are no longer a thing at Google according to this article: https://support.google.com/accounts/answer/6010255?hl=en
At least I haven't found where to enable them...

The same settings work in Calibre so I'm not sure what's going on.

**Comment by majora2007** [comment]
I believe you need port 465 and Allow_SendTo should be true, not "true".

**Comment by lawliet616** [comment]
I've tried that port and different environment settings too.

`ALLOW_SENDTO: true` is appearantly not valid:
services.kavita-email.environment.ALLOW_SENDTO contains true, which is an invalid type, it should be a string, number, or a null

I've tried setting it like this with no success: `- ALLOW_SENDTO=true`

**Comment by majora2007** [comment]
Let me spin this up with docker and test it out.

**Comment by therobbiedavis** [comment]
@lawliet616 Can you exec into your kavita-email container and cat the config/appsettings.json file and verify that the username and password there are the same as your ENV variables?

`docker exec -it <container name> /bin/bash`
`cat /app/config/appsettings.json`

**Comment by akarsten** [comment]
Same issue here. exec'ing into my kavita-email container and cat'ing the conifg/appsettings.json shows the same values as my ENV variables.

**Comment by lawliet616** [comment]
@therobbiedavis The config shows the correct values.

Here's the full config:
```
{
  "ConnectionStrings": {
    "DefaultConnection": "Data source=config/kavita.db"
  },
  "TokenKey": "super secret unguessable key",
  "EnableValidation": false,
  "Serilog": {
    "Using":  [ "Serilog.Sinks.Console", "Serilog.Sinks.File" ],
    "MinimumLevel": "Information",
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "outputTemplate": "[KavitaEmail] [{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} {CorrelationId} {ThreadId}] [{Level}] {SourceContext} {Message:lj}{NewLine}{Exception}"
        }
      },
      { "Name": "File", "Args": {
          "path": "config/logs/kavitaemail.log",
          "outputTemplate": "[KavitaEmail] [{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} {CorrelationId} {ThreadId}] [{Level}] {SourceContext} {Message:lj}{NewLine}{Exception}"
        }
      },
      { "Name": "Seq", "Args": { "serverUrl": "http://localhost:5341", "apiKey": "" } }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
    "Destructure": [
      { "Name": "ToMaximumDepth", "Args": { "maximumDestructuringDepth": 4 } },
      { "Name": "ToMaximumStringLength", "Args": { "maximumStringLength": 100 } },
      { "Name": "ToMaximumCollectionCount", "Args": { "maximumCollectionCount": 10 } }
    ],
    "Properties": {
      "Application": "KavitaEmail"
    }
  },
  "SMTP": {
    "Host": "smtp.gmail.com",
    "Port": "587",
    "UserName": "****@gmail.com",
    "Password": "****",
    "SenderAddress": "****@gmail.com",
    "SenderDisplayName": "gmail",
    "EnableSsl": true,
    "UseDefaultCredentials": false,
    "IsBodyHtml": true,
    "AllowSendTo": true,
    "SizeLimit": 26214400
  }
}
```

**Comment by akarsten** [comment]
I updated the port to 587 and now it works!
