### ISSUE TITLE
Special TLD Emails Not Working

### ISSUE THREAD

**Issue by auntphil** [Kareadita/KavitaEmail#4]
I am using MailGun to send emails and the settings look to be correct. However, it cannot send emails and it appears the system is doing a check on the sender email and does not like special domains. 

I have set my SEND_ADDR to something like library@domain.family. Below is the error message when it tries to send. 

SPECIFIC LINE OF INTEREST
System.FormatException: The specified string is not in the form required for an e-mail address.

FULL ERROR LOG
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMHLU6SHIESP", Request id "0HMHLU6SHIESP:00000002": An unhandled exception was thrown by the application.
      System.FormatException: The specified string is not in the form required for an e-mail address.
         at System.Net.Mail.MailAddressParser.TryReadCfwsAndThrowIfIncomplete(String data, Int32 index, Int32& outIndex, Boolean throwExceptionIfFail)
         at System.Net.Mail.MailAddressParser.TryParseDomain(String data, Int32& index, String& domain, Boolean throwExceptionIfFail)
         at System.Net.Mail.MailAddressParser.TryParseAddress(String data, Boolean expectMultipleAddresses, Int32& index, ParseAddressInfo& parseAddressInfo, Boolean throwExceptionIfFail)
         at System.Net.Mail.MailAddressParser.ParseMultipleAddresses(String data)
         at System.Net.Mail.MailAddressCollection.ParseValue(String addresses)
         at System.Net.Mail.MailAddressCollection.Add(String addresses)
         at Skeleton.Services.EmailService.SendEmail(EmailOptionsDto userEmailOptions) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Services/EmailService.cs:line 104
         at Skeleton.Services.EmailService.SendEmailMigrationEmail(EmailMigrationDto dto) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Services/EmailService.cs:line 68
         at Skeleton.Controllers.EmailController.SendEmailMigrationEmail(EmailMigrationDto dto) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Controllers/EmailController.cs:line 61
         at lambda_method12(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Skeleton.Startup.<>c.<<Configure>b__4_1>d.MoveNext() in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Startup.cs:line 111
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by majora2007** [comment]
Hi, I'm wondering if this is still an issue for you? I know there was a recent release where username wasn't being used for the mailer. 

This issue seems to come from within .Net and not my code. I do no validation on if the email address is valid or not.

**Comment by auntphil** [comment]
I'll be honest I have not tried it recently. I switched to the built in email system and it's been working great. I'll try the custom domain this weekend and to see if it is working.

**Comment by auntphil** [comment]
I have finally come back to try the email relay server again and I can report the issues I was having have gone away and it is working great. The issue was resolved within the .Net.
