### ISSUE TITLE
Gmail app password not accepted

### ISSUE THREAD

**Issue by RobertD502** [Kareadita/KavitaEmail#41]
I'm hitting a wall when it comes to using Gmail to send emails. The following appears in the logs when attempting a test email:

```
[KavitaEmail] [2023-05-07 18:15:22.413 +00:00  ] [Error] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/test responded 500 in 515.8357 ms
MailKit.Security.AuthenticationException: 535: 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials j1-20020a0cf501000000b005ed90bf69efsm2205368qvm.114 - gsmtp
 ---> MailKit.Net.Smtp.SmtpCommandException: 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials j1-20020a0cf501000000b005ed90bf69efsm2205368qvm.114 - gsmtp
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at Skeleton.Services.EmailService.SendEmail(EmailOptionsDto userEmailOptions) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Services/EmailService.cs:line 185
   at Skeleton.Services.EmailService.SendTestEmail(String adminEmail) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Services/EmailService.cs:line 147
   at Skeleton.Controllers.CommonController.Test(String adminEmail, Boolean sendEmail) in /home/runner/work/KavitaEmail/KavitaEmail/KavitaEmail/Controllers/CommonController.cs:line 39
   at lambda_method4(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
```

This is the content of my config:

```
{
  "TokenKey": "super secret unguessable key",
  "Serilog": {
    "Using":  [ "Serilog.Sinks.Console", "Serilog.Sinks.File" ],
    "MinimumLevel": "Debug",
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "outputTemplate": "[KavitaEmail] [{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} {CorrelationId} {ThreadId}] [{Level}] {SourceContext} {Message:lj}{NewLine}{Exception}"
        }
      },
      { "Name": "File", "Args": {
          "path": "config/logs/kavitaemail.log",
          "outputTemplate": "[KavitaEmail] [{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} {CorrelationId} {ThreadId}] [{Level}] {SourceContext} {Message:lj}{NewLine}{Exception}"
        }
      },
      { "Name": "Seq", "Args": { "serverUrl": "http://localhost:5341", "apiKey": "" } }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
    "Destructure": [
      { "Name": "ToMaximumDepth", "Args": { "maximumDestructuringDepth": 4 } },
      { "Name": "ToMaximumStringLength", "Args": { "maximumStringLength": 100 } },
      { "Name": "ToMaximumCollectionCount", "Args": { "maximumCollectionCount": 10 } }
    ],
    "Properties": {
      "Application": "KavitaEmail"
    }
  },
  "SMTP": {
    "Host": "smtp.gmail.com",
    "Port": "587",
    "UserName": "gmailusername@gmail.com",
    "Password": "Gmail app password",
    "SenderAddress": "gmailusername@gmail.com",
    "SenderDisplayName": "Kavita",
    "AllowSendTo": true,
    "SizeLimit": 26214400
  }
}
```

I can confirm that the app password created is correct. I have created multiple and none have worked. I also utilize the app password method for my VaultWarden instance, which works without any issues.

Are there additional SMTP config keys that should be included here that I am missing and could potentially point to the cause of the issue?

**Comment by majora2007** [comment]
I am using Google myself and it's working without problem. 

I don't use `@gmail.com` on the UserName. Can you try like that?

**Comment by RobertD502** [comment]
Tried it just now without `@gmail` in the username and still not working. The same username and password not accepted error is being logged when testing.

**Comment by majora2007** [comment]
Just to clarify, you're restarting between config change and testing correct? Your password doesn't have any +, /, or " in it? Because there is another issue showing there are some problems with those characters.

**Comment by RobertD502** [comment]
Correct. I stop the container, edit appsettings.json, and then start the container again. The password doesn't have any special characters in it. All lowercase letters. The password being used is the app password created for the gmail account and not the main password.

**Comment by RobertD502** [comment]
@majora2007 Found the issue. The sender address is being used for authentication instead of the username from the config.

[Link to code](https://github.com/Kareadita/KavitaEmail/blob/1c5eb7df612ed17b6d0dfaaabf37ce56afba662e/KavitaEmail/Services/EmailService.cs#L185)

**Comment by majora2007** [comment]
Nice find, it's strange that it still works for me. Let me get that patched up for you.

**Comment by RobertD502** [comment]
If you're using the same email for the sender address as the username, it will work. However, it will cause issues if someone is using their gmail to relay messages from a different domain. Perhaps this could also be the cause of the AWS issue that is open?

Thanks for the help!

**Comment by majora2007** [comment]
Thanks again for the help. I've patched it and I'm building new releases now.
